//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColegioBdEntities : DbContext
    {
        public ColegioBdEntities()
            : base("name=ColegioBdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoAula> AlumnoAula { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<GradoAcademico> GradoAcademico { get; set; }
        public virtual DbSet<GradoAcademicoCurso> GradoAcademicoCurso { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Matricula> Matricula { get; set; }
        public virtual DbSet<MatriculaCursoAula> MatriculaCursoAula { get; set; }
        public virtual DbSet<MatriculaCursoProfesor> MatriculaCursoProfesor { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<NotificacionRespuesta> NotificacionRespuesta { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Silabo> Silabo { get; set; }
        public virtual DbSet<TipoGenerico> TipoGenerico { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioAlumno> UsuarioAlumno { get; set; }
    }
}
