//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int HorarioId { get; set; }
        public Nullable<int> GradoAcademicoId { get; set; }
        public Nullable<int> CursoId { get; set; }
        public Nullable<System.DateTime> LunesHoraInicio { get; set; }
        public Nullable<System.DateTime> LunesHoraFin { get; set; }
        public Nullable<System.DateTime> MartesHoraInicio { get; set; }
        public Nullable<System.DateTime> MartesHoraFin { get; set; }
        public Nullable<System.DateTime> MiercolesHoraInicio { get; set; }
        public Nullable<System.DateTime> MiercolesHoraFin { get; set; }
        public Nullable<System.DateTime> JuevesHoraInicio { get; set; }
        public Nullable<System.DateTime> JuevesHoraFin { get; set; }
        public Nullable<System.DateTime> ViernesHoraInicio { get; set; }
        public Nullable<System.DateTime> ViernesHoraFin { get; set; }
        public Nullable<System.DateTime> SabadoHoraInicio { get; set; }
        public Nullable<System.DateTime> SabadoHoraFin { get; set; }
        public Nullable<System.DateTime> DomingoHoraInicio { get; set; }
        public Nullable<System.DateTime> DomingoHoraFIn { get; set; }
        public bool Lunes { get; set; }
        public bool Martes { get; set; }
        public bool Miercoles { get; set; }
        public bool Jueves { get; set; }
        public bool Viernes { get; set; }
        public bool Sabado { get; set; }
        public bool Domingo { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual GradoAcademico GradoAcademico { get; set; }
    }
}
