//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int NotaId { get; set; }
        public Nullable<int> ExamenId { get; set; }
        public int AlumnoId { get; set; }
        public decimal Nota1 { get; set; }
        public string NotaAlfabeto { get; set; }
        public int TipoNotaId { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Examen Examen { get; set; }
        public virtual TipoGenerico TipoGenerico { get; set; }
    }
}
