//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int PermisoId { get; set; }
        public int TipoPermisoId { get; set; }
        public int AlumnoId { get; set; }
        public string Observacion { get; set; }
        public int EstadoPermisoId { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual TipoGenerico TipoGenerico { get; set; }
    }
}
