//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Notificacion = new HashSet<Notificacion>();
            this.UsuarioAlumno = new HashSet<UsuarioAlumno>();
        }
    
        public int UsuarioId { get; set; }
        public string UserName { get; set; }
        public string password { get; set; }
        public string Nombre { get; set; }
        public string ApellidosM { get; set; }
        public string ApellidosP { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> EstadoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAlumno> UsuarioAlumno { get; set; }
    }
}
